#!/usr/bin/env perl

use utf8;
use ESModPP;
use XML::Generator;
use Getopt::Compact;
use Symbol qw/qualify_to_ref/;


my $go = Getopt::Compact->new(
    name    => "EcmaScript MODularizing PreProcessor",
    version => "0.10.1",
    args    => "FILE...",
    struct  => [ [[qw/F filter/], "filter mode"] ]
);
local *opts = $go->opts;


sub error {
    print STDERR @_, "\n";
    exit 1;
}

sub branch {
    my ($src, $eso, $esd) = @_;
    my $p = ESModPP->new;
    binmode $src, ":raw";
    local $/;
    $p->handle($src);
    binmode $eso, ":raw";
    print $eso $p->eof;

    my $gen = XML::Generator->new(":pretty");
    local (*require, *extend);
    *require = [];
    *extend  = [];
    foreach ( qw/require extend/ ) {
        my $mods = $p->$_;
        while ( my ($module, $version) = each %$mods ) {
            push @$_, $gen->$_({ module  => $module,
                                 version => $version || 0 });
        }
    }
    binmode $esd, ":raw";
    binmode $esd, ":utf8";
    print $esd $gen->xmldecl(version => "1.0", encoding => "UTF-8"),
               $gen->esd( { version => "1.0" },
                   $gen->module( { version => $p->version || 0 },
                       @require,
                       @extend,
                   )
               );
}



if ( $opts{filter} ) {
    branch \*STDIN, \*STDOUT, \*STDERR;
    exit;
}


unless ( @ARGV ) {
    print $go->usage;
    exit;
}

foreach my $file ( map{ glob $_ } @ARGV ) {
    open my $src, $file                        or error "Can't open file `$file': $!";
    (my $file_base = $file) =~ s/\.[^.]*$//s;
    open my $eso, ">$file_base.eso"            or error "Can't open file `$file_base.eso': $!";
    open my $esd, ">$file_base.esd"            or error "Can't open file `$file_base.esd': $!";
    local $@;
    eval{ branch $src, $eso, $esd };
    if ( $@ ) {
        $@ =~ /(.*?) at line (\d+)/s;
        error "$1 at $file line $2";
    }
}
